INSERT INTO category (created_by, updated_by, activated_by, state, active, created_at, updated_at, activated_at, sucursal_id, image_url, code, name, description, lang, parent_id)
VALUES
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'electronics.png', UUID(), 'Electronics', 'Devices and gadgets', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'fashion.png', UUID(), 'Fashion', 'Clothing and accessories', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'home_appliances.png', UUID(), 'Home Appliances', 'Household electrical appliances', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'beauty_health.png', UUID(), 'Beauty & Health', 'Cosmetics and healthcare products', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'sports.png', UUID(), 'Sports', 'Sports gear and equipment', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'automotive.png', UUID(), 'Automotive', 'Car accessories and parts', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'toys.png', UUID(), 'Toys', 'Toys and games for all ages', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'books.png', UUID(), 'Books', 'Books and literature', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'furniture.png', UUID(), 'Furniture', 'Home and office furniture', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'groceries.png', UUID(), 'Groceries', 'Food and household essentials', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'pet_supplies.png', UUID(), 'Pet Supplies', 'Food and accessories for pets', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'jewelry.png', UUID(), 'Jewelry', 'Luxury and fashion jewelry', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'gaming.png', UUID(), 'Gaming', 'Video games and accessories', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'baby_products.png', UUID(), 'Baby Products', 'Baby care and essentials', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'office_supplies.png', UUID(), 'Office Supplies', 'Stationery and office equipment', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'tools.png', UUID(), 'Tools & Hardware', 'DIY and industrial tools', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'music.png', UUID(), 'Music', 'Musical instruments and accessories', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'art_crafts.png', UUID(), 'Art & Crafts', 'DIY and artistic materials', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'smart_home.png', UUID(), 'Smart Home', 'Home automation and IoT devices', 'en', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'eletronicos.png', UUID(), 'Eletronicos', 'Dispositivos Eletronicos', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'moda.png', UUID(), 'Moda', 'Roupas e acessórios', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'eletrodomesticos.png', UUID(), 'Eletrodomésticos', 'Aparelhos elétricos domésticos', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'beleza_saude.png', UUID(), 'Beleza & Saúde', 'Cosméticos e produtos de saúde', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'esportes.png', UUID(), 'Desporto', 'Equipamentos e acessórios esportivos', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'automotivo.png', UUID(), 'Automotivo', 'Acessórios e peças para carros', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'brinquedos.png', UUID(), 'Brinquedos', 'Brinquedos e jogos para todas as idades', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'livros.png', UUID(), 'Livros', 'Livros e literatura', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'moveis.png', UUID(), 'Móveis', 'Móveis para casa e escritório', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'mercado.png', UUID(), 'Mercado', 'Alimentos e itens essenciais para o lar', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'petshop.png', UUID(), 'Produtos para animais de estimação', 'Alimentos e acessórios para animais de estimação', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'joias.png', UUID(), 'Joias', 'Joias de luxo e bijuterias', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'games.png', UUID(), 'Games', 'Videogames e acessórios', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'bebe.png', UUID(), 'Produtos para Bebês', 'Cuidados e itens essenciais para bebês', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'escritorio.png', UUID(), 'Material de Escritório', 'Papelaria e equipamentos para escritório', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'ferramentas.png', UUID(), 'Ferramentas & Hardware', 'Ferramentas para DIY e uso industrial', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'musica.png', UUID(), 'Música', 'Instrumentos musicais e acessórios', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'artesanato.png', UUID(), 'Artes & Artesanato', 'Materiais para DIY e arte', 'pt', NULL),
    (1, NULL, 1, 0, TRUE, NOW(), NULL, NOW(), 1, 'casa_inteligente.png', UUID(), 'Casa Inteligente', 'Automação residencial e dispositivos IoT', 'pt', NULL);

INSERT INTO unit (code, description, lang, created_by, activated_by, state, active, created_at, activated_at, sucursal_id)
VALUES
    ('000', 'Unit (s)', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('001', 'Kilogram', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('002', 'Litre', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('003', 'Meter', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('004', 'Centimeter', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('005', 'Millimeter', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('006', 'Box', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('007', 'Piece', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('008', 'Pack', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('009', 'Dozen', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('010', 'Gram', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('011', 'Ton', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('012', 'Yard', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('013', 'Foot', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('014', 'Inch', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('015', 'Gallon', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('016', 'Barrel', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('017', 'Sack', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('018', 'Pair', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('019', 'Bundle', 'en',1,1, 0, TRUE, NOW(), NOW(),1),
    ('020', 'Carton', 'en',1,1, 0, TRUE, NOW(), NOW(),1),

    ('030', 'Unidade (s)', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('031', 'Quilograma', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('032', 'Litro', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('033', 'Metro', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('034', 'Centímetro', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('035', 'Milímetro', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('036', 'Caixa', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('037', 'Peça', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('038', 'Pacote', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('039', 'Dúzia', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('030', 'Grama', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('031', 'Tonelada', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('032', 'Jarda', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('033', 'Pé', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('034', 'Polegada', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('035', 'Galão', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('036', 'Barril', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('037', 'Saco', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('038', 'Par', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('039', 'Feixe', 'pt',1,1, 0, TRUE, NOW(), NOW(),1),
    ('040', 'Cartão', 'pt',1,1, 0, TRUE, NOW(), NOW(),1);

